version: 1
builder:
  configs:
    - scheme: xtool
      platform: macosSpm
      documentation_targets:
      - xtool
    - scheme: xtool
      platform: macosXcodebuild
    - scheme: xtool
      platform: linux
      image: kabiroberai/xtool-dev:latest
    - scheme: XKit
      platform: ios
