[build]
  # by setting a custom base directory, we prevent Netlify from running
  # `swift build` in the root directory, which builds more targets than
  # we need.
  base = "Netlify/"
  publish = "docs/"
  command = "./build.sh"
  environment = { SWIFT_VERSION = "6.1" }
  ignore = "git -C .. diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- Sources/XToolDocs Netlify"

[[redirects]]
  from = "/"
  to = "/documentation/xtooldocs/"
  status = 302
  force = true

[[redirects]]
  from = "/documentation"
  to = "/documentation/xtooldocs/"
  status = 302
  force = true

[[redirects]]
  from = "/tutorials"
  to = "/tutorials/toc"
  status = 302
  force = true

[[redirects]]
  from = "/documentation/xtool/*"
  to = "/documentation/xtooldocs/:splat"
  status = 302

[[redirects]]
  from = "/tutorials/xtool/*"
  to = "/tutorials/xtooldocs/:splat"
  status = 302
