overlay: 1.0.0
info:
  title: Overlay for App Store Connect API
  version: 1.0.0
actions:
  # openapi-generator expects response enums to be exhaustive. Apple's ASC OpenAPI spec
  # misses some cases that they do, actually, return.
  - target: '$.components.schemas.Device.properties.attributes.properties.deviceClass'
    update:
      enum:
        - APPLE_VISION_PRO
  - target: '$.components.schemas.BundleIdPlatform'
    update:
      enum:
        - SERVICES
        # the spec already declares MAC_OS but ASC sometimes seems to
        # spell this as MACOS instead. see:
        # https://github.com/xtool-org/xtool/issues/64
        - MACOS
