on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        # based on https://github.com/norio-nomura/action-swiftlint
        run: |
          function stripPWD() {
            ! ${WORKING_DIRECTORY+false} && cd - > /dev/null
            sed -E "s/$(pwd|sed 's/\//\\\//g')\///"
          }
          swift package plugin --allow-writing-to-package-directory swiftlint | \
            stripPWD | \
            sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'
