on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: |
          curl -fSLO https://github.com/realm/SwiftLint/releases/download/0.59.1/swiftlint_linux.zip
          unzip swiftlint_linux.zip swiftlint -d /usr/local/bin
          rm swiftlint_linux.zip
      - name: Lint
        # based on https://github.com/norio-nomura/action-swiftlint
        run: |
          set -o pipefail
          swiftlint --strict | sed -E \
              -e "s/$(pwd|sed 's/\//\\\//g')\///"
              -e 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'
