on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          make lint SWIFTLINT_FLAGS='--reporter=github-actions-logging' | tee swiftlint.log
          # fail if there are any errors or warnings
          ! grep -Eq '^::(error|warning)' swiftlint.log
