on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        # based on https://github.com/norio-nomura/action-swiftlint
        run: |
          make lint \
            | sed -E \
              -e "s/$(pwd|sed 's/\//\\\//g')\///" \
              -e 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/' \
            | tee swiftlint.log
          # fail if there are any errors or warnings
          ! grep -Eq '^::(error|warning)' swiftlint.log
